// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, wpm, accuracy, completed_at)
      VALUES ($1, $2, $3, $4)
      RETURNING id, wpm, accuracy, completed_at
`

type CreateSessionParams struct {
	UserID      pgtype.UUID
	Wpm         int32
	Accuracy    pgtype.Numeric
	CompletedAt pgtype.Timestamptz
}

type CreateSessionRow struct {
	ID          pgtype.UUID
	Wpm         int32
	Accuracy    pgtype.Numeric
	CompletedAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.Wpm,
		arg.Accuracy,
		arg.CompletedAt,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.Wpm,
		&i.Accuracy,
		&i.CompletedAt,
	)
	return i, err
}
