name: Local
variables:
  - name: baseUrl
    value: http://localhost:8080
  - name: userEmail
    value: dev@example.com
  - name: userPassword
    value: password123
  - secret: true
    name: token
  - name: sessionCursor
    value: ""
