// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthCredential struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	CredKind   string
	Identifier string
	Secret     *string
	CreatedAt  pgtype.Timestamptz
}

type Session struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Wpm         int32
	Accuracy    pgtype.Numeric
	CompletedAt pgtype.Timestamptz
}

type User struct {
	ID          pgtype.UUID
	DisplayName *string
	CreatedAt   pgtype.Timestamptz
}

type UserProgress struct {
	UserID     pgtype.UUID
	Competency []byte
	UpdatedAt  pgtype.Timestamptz
}
