// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserProgress = `-- name: CreateUserProgress :exec
INSERT INTO user_progress (user_id, competency)
VALUES ($1, $2)
`

type CreateUserProgressParams struct {
	UserID     pgtype.UUID
	Competency []byte
}

func (q *Queries) CreateUserProgress(ctx context.Context, arg CreateUserProgressParams) error {
	_, err := q.db.Exec(ctx, createUserProgress, arg.UserID, arg.Competency)
	return err
}

const getUserProgress = `-- name: GetUserProgress :one
SELECT competency
FROM user_progress
WHERE user_id = $1
`

func (q *Queries) GetUserProgress(ctx context.Context, userID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getUserProgress, userID)
	var competency []byte
	err := row.Scan(&competency)
	return competency, err
}

const getUserProgressForUpdate = `-- name: GetUserProgressForUpdate :one
SELECT competency
FROM user_progress
WHERE user_id = $1
FOR UPDATE
`

func (q *Queries) GetUserProgressForUpdate(ctx context.Context, userID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getUserProgressForUpdate, userID)
	var competency []byte
	err := row.Scan(&competency)
	return competency, err
}

const updateUserProgress = `-- name: UpdateUserProgress :exec
UPDATE user_progress
SET competency = $2, updated_at = now()
WHERE user_id = $1
`

type UpdateUserProgressParams struct {
	UserID     pgtype.UUID
	Competency []byte
}

func (q *Queries) UpdateUserProgress(ctx context.Context, arg UpdateUserProgressParams) error {
	_, err := q.db.Exec(ctx, updateUserProgress, arg.UserID, arg.Competency)
	return err
}
