// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserProgress = `-- name: CreateUserProgress :exec
INSERT INTO user_progress (user_id, competency)
VALUES ($1, $2)
`

type CreateUserProgressParams struct {
	UserID     pgtype.UUID
	Competency []byte
}

func (q *Queries) CreateUserProgress(ctx context.Context, arg CreateUserProgressParams) error {
	_, err := q.db.Exec(ctx, createUserProgress, arg.UserID, arg.Competency)
	return err
}
