// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateUserProgress(ctx context.Context, arg CreateUserProgressParams) error
}

var _ Querier = (*Queries)(nil)
