// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCredential(ctx context.Context, arg CreateCredentialParams) error
	CreateUser(ctx context.Context) (pgtype.UUID, error)
	PasswordCredentialExists(ctx context.Context, identifier string) (bool, error)
}

var _ Querier = (*Queries)(nil)
