// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredential = `-- name: CreateCredential :exec
INSERT INTO auth_credentials (user_id, cred_kind, identifier, secret)
VALUES ($1, $2, $3, $4)
`

type CreateCredentialParams struct {
	UserID     pgtype.UUID
	CredKind   string
	Identifier string
	Secret     *string
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.Exec(ctx, createCredential,
		arg.UserID,
		arg.CredKind,
		arg.Identifier,
		arg.Secret,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users DEFAULT VALUES
RETURNING id
`

func (q *Queries) CreateUser(ctx context.Context) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUser)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getCredentialByIdentifier = `-- name: GetCredentialByIdentifier :one
SELECT user_id, secret
  FROM auth_credentials
  WHERE cred_kind = 'password'
  AND identifier = $1
`

type GetCredentialByIdentifierRow struct {
	UserID pgtype.UUID
	Secret *string
}

func (q *Queries) GetCredentialByIdentifier(ctx context.Context, identifier string) (GetCredentialByIdentifierRow, error) {
	row := q.db.QueryRow(ctx, getCredentialByIdentifier, identifier)
	var i GetCredentialByIdentifierRow
	err := row.Scan(&i.UserID, &i.Secret)
	return i, err
}

const passwordCredentialExists = `-- name: PasswordCredentialExists :one
SELECT EXISTS (
SELECT 1
  FROM auth_credentials
  WHERE cred_kind = 'password'
  AND identifier = $1
)
`

func (q *Queries) PasswordCredentialExists(ctx context.Context, identifier string) (bool, error) {
	row := q.db.QueryRow(ctx, passwordCredentialExists, identifier)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
